config/routes.rb
Project2::Application.routes.draw do
  get "landing/index"

  resources :companies
  resources :employees
  resources :timemanagements
  resources :salaries
  resources :leaves

  root :to => 'landing#index'

end

app/models/company.rb
class Company < ActiveRecord::Base
  #validates_presence_of :group_name, :company_name, :responsible_person, :company_type, :address, :city, :state, :country , :message => "Field should not be empty! "
  #validates_uniqueness_of :company_name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all

    respond_to do |format|
      format.html # index.html.haml
      format.json { render json: @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = Company.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.json
  def new
    @company = Company.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(params[:company])

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render json: @company, status: :created, location: @company }
      else
        format.html { render action: "new" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.json
  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :ok }
    end
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  # To change this template use File | Settings | File Templates
  #
  #
  def test
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end
end

app/controllers/leaves_controller.rb
class LeavesController < ApplicationController
  # To change this template use File | Settings | File Templates.
end

app/controllers/salaries_controller.rb
class SalariesController < ApplicationController
  # To change this template use File | Settings | File Templates.
end

app/controllers/timemanagements_controller.rb
class TimemanagementsController < ApplicationController
  # To change this template use File | Settings | File Templates.

def show
  respond_to do |format|
    format.html #showhtml.haml
  end
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/views/companies/_common.html.haml
#header
  %h1
    Welcome Aditya! You are logged in as Administrator
    %br>/
    #{Time.now.strftime("%d %b %Y, %I:%M %p")}
#menu
  %ul
    %li
      %a{:href => root_url} HOME
    %li
      %a.selected{:href => companies_path} COMPANY
    %li
      %a{:href => employees_path} EMPLOYEE
    %li
      %a{:href => timemanagements_path} TA
    %li
      %a{:href => salaries_path} SALARY
    %li
      %a{:href => leaves_path} LEAVE
.below_border &nbsp;
#left-content
  .left_box
    .left_box_header
      %h1 Company's Quick Links
    %p
      %a{:href => '#'} Groups
      %br/
      %a{:href => companies_path} Company List

app/views/companies/_form.html.haml
%script{:src => "companies.js", :type => "text/javascript"}

%link{:href => "example.css", :media => "screen", :rel => "stylesheet", :type => "text/css"}/

:javascript
  /* Optional: Temporarily hide the "tabber" class so it does not "flash"
     on the page as plain HTML. After tabber runs, the class is changed
     to "tabberlive" and it will appear. */

  document.write('<style type="text/css">.tabber{display:none;}<\/style>');
= form_for(@company) do |f|
  - if @company.errors.any?
    #error_explanation
      %h2
        = pluralize(@company.errors.count, "error")
        prohibited this company from being saved:
      %ul
        - @company.errors.full_messages.each do |msg|
          %li= msg
  #form
    .tabber
      .tabbertab
        %h2 Company Details
        %div
          %table.disp_data{:align => "center", :cellpadding => "5", :cellspacing => "0"}
            %tr
              %td{:width => "50%"}
                %table{:cellpadding => "0", :cellspacing => "0", :width => "100%"}
                  %tr
                    %td.td_width.main_title{:colspan => "2"}
                      Company Details:
                  %tr
                    %td.td_height_form
                  %tr
                    %td.td_width
                      Group Name:
                    %td= f.text_field :group_name
                  %tr
                    %td.td_width
                      Company Name:
                    %td= f.text_field :company_name
                  %tr
                    %td.td_width
                      Establish Date:
                    %td= f.date_select :establishment_date
                  %tr
                    %td.td_width
                      Company Logo:
                    %td= f.text_field :company_logo
                  %tr
                    %td.spacing
                  %tr
                    %td.td_width.main_title{:colspan => "2"}
                      Address Details:
                  %tr
                    %td.td_height_form{:colspan => "2"}
                  %tr
                    %td.td_width
                      Address:
                    %td= f.text_field :address
                  %tr
                    %td.td_width
                      State:
                    %td= f.text_field :state
                  %tr
                    %td.spacing
                  %tr
                    %td.td_width.main_title{:colspan => "2"}
                      Contact Details:
                  %tr
                    %td.td_height_form{:colspan => "2"}
                  %tr
                    %td.td_width
                      Contact No:
                    %td= f.number_field :contact_one
                  %tr
                    %td.td_width
                      Email:
                    %td= f.text_field :email
                  %tr
                    %td.td_width
                      Fax:
                    %td= f.number_field :fax
                  %tr
                    %td.spacing
              %td{:width => "50%"}
                %table{:cellpadding => "0", :cellspacing => "0", :width => "100%"}
                  %tr
                    %td.td_width
                  %tr
                    %td.td_height_form
                  %tr
                    %td.td_width
                  %tr
                    %td.td_width
                      Resp. Person:
                    %td= f.text_field :responsible_person
                  %tr
                    %td.td_width
                      Company Type:
                    %td= f.text_field :company_type
                  %tr
                    %td.td_width
                    %td
                  %tr
                    %td.spacing
                  %tr
                    %td.td_width
                  %tr
                    %td.td_height_form
                  %tr
                    %td.td_width
                      City:
                    %td= f.text_field :city
                  %tr
                    %td.td_width
                      Country:
                    %td= f.text_field :country
                  %tr
                    %td.spacing
                  %tr
                    %td.td_width
                  %tr
                    %td.td_height_form
                  %tr
                    %td.td_width
                      Alternate No:
                    %td= f.number_field :contact_two
                  %tr
                    %td.td_width
                      Alternate Email:
                    %td= f.text_field :email2
                  %tr
                    %td.td_width
                      Website:
                    %td= f.text_field :website
                  %tr
                    %td.spacing
      .tabbertab
        %h2 PF/ESI Details
        %div
          %table.disp_data{:align => "center", :cellpadding => "5", :cellspacing => "0"}
            %tr
              %td{:width => "50%"}
                %table{:cellpadding => "0", :cellspacing => "0", :width => "100%"}
                  %tr
                    %td.td_width.main_title{:colspan => "2"}
                      PF Details:
                  %tr
                    %td.td_height_form
                  %tr
                    %td.td_width
                      Company PF No.:
                    %td
                      %input{:name => "txtCompPFNo", :size => "30", :type => "text", :value => "KN/4564B"}/
                  %tr
                    %td.td_width
                      DBF File - Code:
                    %td
                      %input{:name => "txtDBF", :size => "30", :type => "text", :value => "56455"}/
                  %tr
                    %td.td_width
                      Extension:
                    %td
                      %input{:name => "txtExtn", :size => "30", :type => "text", :value => "2"}/
                  %tr
                    %td.spacing
                  %tr
                    %td.td_width.main_title{:colspan => "2"}
                      ESI Details:
                  %tr
                    %td.td_height_form
                  %tr
                    %td.td_width
                      Company ESI No.:
                    %td
                      %input{:name => "txtCompESINo", :size => "30", :type => "text", :value => "KN/344/ESI"}/
                  %tr
                    %td.td_width
                      ESI Local Office:
                    %td
                      %input{:name => "txtESIOffice", :size => "30", :type => "text", :value => "123 Street, Mumbai"}/
                  %tr
                    %td.td_width
                      &nbsp;
                  %tr
                    %td.spacing
              %td{:width => "50%"}
                %table{:cellpadding => "0", :cellspacing => "0", :width => "100%"}
                  %tr
                    %td.td_width
                  %tr
                    %td.td_height_form
                  %tr
                    %td.td_width
                      PF Vol.:
                    %td
                      %input{:name => "chkPFVol", :size => "30", :type => "checkbox", :checked => 'checked'}/
                  %tr
                    %td.td_width
                      Multiple Group:
                    %td
                      %input{:name => "chkPFMulti", :size => "30", :type => "checkbox"}/
                  %tr
                    %td.td_width
                      &nbsp;
                  %tr
                    %td.spacing
                  %tr
                    %td.td_width
                  %tr
                    %td.td_height_form
                  %tr
                    %td.td_width
                      Individually Calculate ESI:
                    %td
                      %input{:name => "chkCalESI", :size => "30", :type => "checkbox", :checked => 'checked'}/
                  %tr
                    %td.td_width
                      Limit ESI Gross:
                    %td
                      %input{:name => "chkESIGross", :size => "30", :type => "checkbox", :checked => 'checked'}/
                  %tr
                    %td.td_width
                      Multiple Group:
                    %td
                      %input{:name => "chkESIMulti", :size => "30", :type => "checkbox"}/
                  %tr
                    %td.spacing
      .tabbertab
        %h2 Branch Details
        %div
          %table.disp_data{:align => "center", :cellpadding => "5", :cellspacing => "0"}
            %tr
              %td{:width => "50%"}
                %table{:cellpadding => "0", :cellspacing => "0", :width => "100%"}
                  %tr
                    %td.td_width.main_title{:colspan => "2"}
                      Branch Details:
                  %tr
                    %td.td_height_form
                  %tr
                    %td.td_width
                      Branch:
                    %td
                      %input{:name => "txtBranch", :size => "30", :type => "text", :value => "Bangalore WDO"}/
                  %tr
                    %td.td_width
                      Resp. Person:
                    %td
                      %input{:name => "txtResPersonBranch", :size => "30", :type => "text", :value => "MAnjunath"}/
                  %tr
                    %td.td_width
                      Address:
                    %td
                      %input{:name => "txtBranchAdd", :size => "30", :type => "text", :value => "2nd Cross, 10th Main"}/
                  %tr
                    %td.td_width
                      PF Group:
                    %td
                      %input{:name => "txtBranchPF", :size => "30", :type => "text", :value => "Bangalore"}/
                  %tr
                    %td.td_width
                      PT Group:
                    %td
                      %input{:name => "txtBranchPT", :size => "30", :type => "text", :value => "Bangalore"}/
                  %tr
                    %td.td_width
                      ESI Group:
                    %td
                      %input{:name => "txtBranchESI", :size => "30", :type => "text", :value => "Bangalore"}/
                  %tr
                    %td.spacing

              %td{:width => "50%"}

      #form_button
        .actions= f.submit

app/views/companies/edit.html.haml
#page
  = render "common"
  #right-content
    %h1 Editing Company
    = render 'form'
    = link_to 'Show', @company
    |
    \#{link_to 'Back', companies_path}

app/views/companies/index.html.haml
#page
  = render "common"
  #right-content
    = link_to 'Add New Company', new_company_path
    %h1 Listing Companies
    %table{:align => "left", :cellpadding => "0", :cellspacing => "0", :width => "900"}
      %tr
        %th.b Group name
        %th.btrb Company name
        %th.btrb Responsible person
        %th.btrb Establishment date
        %th.btrb Company type
        %th.btrb{:colspan => "3"} Operation
      - @companies.each do |company|
        %tr
          %td.blrb= company.group_name
          %td.brb= company.company_name
          %td.brb= company.responsible_person
          %td.brb= l company.establishment_date, :format => :default
          %td.brb= company.company_type
          %td.brb= link_to 'Show', company
          %td.brb= link_to 'Edit', edit_company_path(company)
          %td.brb= link_to 'Destroy', company, confirm: 'Are you sure?', method: :delete
    %br/

app/views/companies/new.html.haml
#page
  = render "common"
  #right-content
    %h1 New Company
    = render 'form'
    /= link_to 'Back', companies_path

app/views/companies/show.html.haml
#page
  = render "common"
  #right-content
    %p#notice= notice
    %h1 Company Details
    %table.disp_data{:align => "center", :cellpadding => "5", :cellspacing => "0"}
      %tr
        %td{:width => "50%"}
          %table{:cellpadding => "0", :cellspacing => "0", :width => "100%"}
            %tr
              %td.td_width.main_title{:colspan => "2"}
                Company Details:
            %tr
              %td.td_width
                Group Name:
              %td= @company.group_name
            %tr
              %td.td_width
                Company Name:
              %td= @company.company_name
            %tr
              %td.td_width
                Establish Date:
              %td= l @company.establishment_date, :format => :default
            %tr
              %td.td_width
                Company Logo:
              %td= @company.company_logo
            %tr
              %td.spacing
            %tr
              %td.td_width.main_title{:colspan => "2"}
                Address Details:
            %tr
              %td.td_width
                Address:
              %td= @company.address
            %tr
              %td.td_width
                State:
              %td= @company.state
            %tr
              %td.spacing
            %tr
              %td.td_width.main_title{:colspan => "2"}
                Contact Details:
            %tr
              %td.td_width
                Contact No:
              %td= @company.contact_one
            %tr
              %td.td_width
                Email:
              %td= @company.email
            %tr
              %td.td_width
                Fax:
              %td= @company.fax
            %tr
              %td.spacing
            %tr
              %td.td_width.main_title{:colspan => "2"}
                PF Details:
            %tr
              %td.td_width
                Company PF No:
              %td KN/4564B
            %tr
              %td.td_width
                DBF File - Code:
              %td 56455
            %tr
              %td.td_width
                Extension:
              %td 2
            %tr
              %td.spacing
            %tr
              %td.td_width.main_title{:colspan => "2"}
                ESI Details:
            %tr
              %td.td_width
                Company ESI No:
              %td KN/344/ESI
            %tr
              %td.td_width
                ESI Local Address:
              %td 123 Street, Bangalore
            %tr
              %td.td_width
              %td &nbsp;
            %tr
              %td.spacing
            %tr
              %td.td_width.main_title{:colspan => "2"}
                Branch Details:
            %tr
              %td.td_width
                Branch:
              %td Bangalore WDO
            %tr
              %td.td_width
                Resp. Person:
              %td Manjunath
            %tr
              %td.td_width
                Address:
              %td 2nd Cross, 10th Main
            %tr
              %td.td_width
                PF Group:
              %td Bangalore
            %tr
              %td.td_width
                PT Group:
              %td Bangalore
            %tr
              %td.td_width
                ESI Group:
              %td Bangalore
            %tr
              %td.spacing
        %td{:width => "50%"}
          %table{:cellpadding => "0", :cellspacing => "0", :width => "100%"}
            %tr
              %td.td_width
            %tr
              %td.td_width
            %tr
              %td.td_width
                Resp. Person:
              %td= @company.responsible_person
            %tr
              %td.td_width
                Company Type:
              %td= @company.company_type
            %tr
              %td.spacing
            %tr
              %td.td_width
              %td &nbsp;
            %tr
              %td.td_width
              %td &nbsp;
            %tr
              %td.td_width
                City:
              %td= @company.city
            %tr
              %td.td_width
                Country:
              %td= @company.country
            %tr
              %td.spacing
            %tr
              %td.td_width
            %tr
              %td.td_width
                Alternate No:
              %td= @company.contact_two
            %tr
              %td.td_width
                Alternate Email:
              %td= @company.email2
            %tr
              %td.td_width
                Website:
              %td= @company.website
            %tr
              %td.spacing
            %tr
              %td.td_width
            %tr
              %td.td_width
                PF Vol.:
              %td Yes
            %tr
              %td.td_width
                Multiple Group:
              %td No
            %tr
              %td.td_width
              %td &nbsp;
            %tr
              %td.spacing
            %tr
              %td.td_width
            %tr
              %td.td_width
                Individually Calculate ESI:
              %td Yes
            %tr
              %td.td_width
                Limit ESI Gross:
              %td Yes
            %tr
              %td.td_width
                Multiple Group:
              %td No
            %tr
              %td.spacing
            %tr
              %td.td_width
            %tr
              %td.td_width
            %tr
              %td.td_width
            %tr
              %td.td_width
            %tr
              %td.td_width
            %tr
              %td.td_width
            %tr
              %td.td_width
    = link_to 'Edit', edit_company_path(@company)
    |
    \#{link_to 'Back', companies_path}

app/views/employees/_common.html.haml
#header
  %h1
    Welcome Aditya! You are logged in as Administrator
    %br>/
    #{Time.now.strftime("%d %b %Y, %I:%M %p")}
#menu
  %ul
    %li
      %a{:href => root_url} HOME
    %li
      %a{:href => companies_path} COMPANY
    %li
      %a.selected{:href => employees_path} EMPLOYEE
    %li
      %a{:href => timemanagements_path} TA
    %li
      %a{:href => salaries_path} SALARY
    %li
      %a{:href => leaves_path} LEAVE
.below_border &nbsp;
#left-content
  .left_box
    .left_box_header
      %h1 Company's Quick Links
    %p
      %a{:href => employees_path} Employee
      %br/
      %a{:href => root_url + "employees/new"} New
      %br/

app/views/employees/index.html.erb
#page

app/views/employees/index.html.haml
#page
  = render "common"
  #right-content
    %h1 Employee Details
    %table{:align => "left", :cellpadding => "0", :cellspacing => "0", :width => "900"}
      %tr
        %th.b Ref No
        %th.btrb Emp ID
        %th.btrb Employee Name
        %th.btrb{:colspan => "3"} Operation
      /- @companies.each do |company|
      %tr
        %td.blrb= "1406"
        %td.brb= "1406"
        %td.brb= "Ranjeet Kumar"
        %td.brb= link_to 'Show', "#"
        %td.brb= link_to 'Edit', "#"#edit_company_path(company)
        %td.brb= link_to 'Destroy',"#" #company, confirm: 'Are you sure?', method: :delete
      %tr
        %td.blrb= "1506"
        %td.brb= "1506"
        %td.brb= "Aditya Swaroop"
        %td.brb= link_to 'Show', "#"
        %td.brb= link_to 'Edit', "#"#edit_company_path(company)
        %td.brb= link_to 'Destroy',"#" #company, confirm: 'Are you sure?', method: :delete
      %tr
        %td.blrb= "2506"
        %td.brb= "2506"
        %td.brb= "Rohini R"
        %td.brb= link_to 'Show', "#"
        %td.brb= link_to 'Edit', "#" #edit_company_path(company)
        %td.brb= link_to 'Destroy',"#" #company, confirm: 'Are you sure?', method: :delete
    %br/

app/views/employees/new.html.haml
:javascript
  function fnShowSetCation()
  {
      var w = 1000;
      var h = 300;
      var left = (screen.width/2)-(w/2);
      var top = (screen.height/2)-(h/2);
      var targetWin = window.open ('SetCaption', 'SetCaption', 'toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=no, resizable=no, copyhistory=no, width='+w+', height='+h+', top='+top+', left='+left);
  }
#page
  = render "common"
  #right-content
    %h1 New Employee
    = render "form"
    %input{:name => "", :type => "button", :value => "Create Employee"}
    %input{:name => "", :type => "button", :value => "SetCaption", :onclick => "fnShowSetCation()"}

app/views/landing/index.html.haml
#page
  #header
    %h1
      Welcome Aditya! You are logged in as Administrator
      %br>/
      #{Time.now.strftime("%d %b %Y, %I:%M %p")}
  #menu
    %ul
      %li
        %a.selected{:href => root_url} HOME
      %li
        %a{:href => companies_path} COMPANY
      %li
        %a{:href => employees_path} EMPLOYEE
      %li
        %a{:href => timemanagements_path} TA
      %li
        %a{:href => salaries_path} SALARY
      %li
        %a{:href => leaves_path} LEAVE
  .below_border &nbsp;
  #left-content
    .left_box
      .left_box_header
        %h1 ToolTips
      %p Use up and down arrow keys to select the vertical navigators in employees summary
    .left_box
      .left_box_header
        %h1 Quick Links
      %p
        %a{:href => "#"} About Us
        %br/
        %a{:href => "#"} Contact Us
        %br/
        %a{:href => "#"} Privacy Policy
    .left_box
      .left_box_header
        %h1 Relyonsoft @ Twitter
      %p
        %a{:href => "#"} For e-file ITRs, you can send ITR-V...
        %br/
        %a{:href => "#"} New System Introduced at TIN...
        %br/
        %a{:href => "#"} Requesting all TAN holders...
        %br/
        %a{:href => "#"} Contact your nearest Relyon Office...
        %br/
        %a{:href => "#"} Get Free Income Tax Software...
        %br/
        %a{:href => "#"} Income Tax Return filing due date...
        %br/
        %a{:href => "#"} NEW: Check you TDS Defaults...
        %br/
  #right-content
    %h1 Welcome to SPP Web Plugin: A Complete Payroll System
    %h2 For Employer
    %ul
      %li Payroll
      %span
        SPP Web Plugin provides flexible payroll services that improve payroll management for employers of small, medium, or large businesses. SPP Web Plugin payroll solutions streamline your payroll process, improve productivity and simplify administration. We manage the time-consuming tasks of payroll processing and employees payroll tax filing so you can focus on running your business. SPP Web Plugin payroll solutions ensure that your payroll needs are met on time, every time.&nbsp;&nbsp;&nbsp;&nbsp;
        %span
          %a{:href => "#"} Read More...
      %li HR
      %span
        Automating the many processes surrounding human resource management enables you and your staff to become more efficient and effective and focus on your organization’s core competencies. Whether your needs are to reduce the manual workload, empower your managers and employees through self service options, or more effectively manage your human capital, SPP Web Plugin suite of HR services can help. &nbsp;&nbsp;&nbsp;&nbsp;
        %span
          %a{:href => "#"} Read More...
      %li Benefit Services
      %span
        SPP Web Plugin offers a comprehensive, single-source solution for outsourced benefits administration. SPP Web Plugin provides employers with simplified benefits management that fits the specific needs of their organization — regardless of company size.&nbsp;&nbsp;&nbsp;&nbsp;
        %span
          %a{:href => "#"} Read More...
      %li Tax & Compliance
      %span
        Staying current on constantly changing tax and unemployment laws and regulations, meeting strict government deadlines, and avoiding costly fines and penalties can be an administrative burden for a company of any size.
        %br/
        SPP Web Plugin Tax & Compliance Services is well versed in governmental regulations and well positioned to help employers to reduce expenses, eliminate manual tasks, and allocate resources for other strategic activities. &nbsp;&nbsp;&nbsp;&nbsp;
        %span
          %a{:href => "#"} Read More...
      %li
        %a{:href => "#"} More Services
  #footer
    \&copy; Copyright 2011, Relyon Softech Limited
    %br>/
    All Rights Reserved.

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title SPP Web Plugin: A Complete Payroll System
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = yield

app/views/leaves/_common.html.haml
#header
  %h1
    Welcome Aditya! You are logged in as Administrator
    %br>/
    #{Time.now.strftime("%d %b %Y, %I:%M %p")}
#menu
  %ul
    %li
      %a{:href => root_url} HOME
    %li
      %a{:href => companies_path} COMPANY
    %li
      %a{:href => employees_path} EMPLOYEE
    %li
      %a{:href => timemanagements_path} TA
    %li
      %a{:href => salaries_path} SALARY
    %li
      %a.selected{:href => employees_path} LEAVE
.below_border &nbsp;
#left-content
  .left_box
    .left_box_header
      %h1 Leave Module Links
    %p
      %a{:href => leaves_path} Leave
      %br/
      %a{:href => "#"} Add New Leave
      %br/
      %a{:href => "#"} Configure Attendance
      %br/
      %a{:href => "#"} General Settings
      %br/
      %a{:href => "#"} Holiday List
      %br/

app/views/leaves/_generalsettings.html.haml
!!!
%html{:xmlns => "http://www.w3.org/1999/xhtml"}
  %head
    %title
  %body
    %div{:style => "border-style: solid; width: 400px"}
      %table{:style => "width:100%;"}
        %tr
          %td{:align => "center", :colspan => "2", :style => "font-family: Verdana; font-size: large; font-weight: bold;"}
            General Settings
            %hr/
        %tr
          %td{:style => "font-family: Verdana; font-size: small; font-weight: bold; width:60%"}
            Basic Settings
          %td{:style => "font-family: Verdana; font-size: small"}
        %tr
          %td{:style => "font-family: Verdana; font-size: small"}
            Consider Exess Leave as LOP
          %td{:style => "font-family: Verdana; font-size: small"}
            %input#cbExcessLeave{:type => "checkbox"}/
        %tr
          %td{:style => "font-family: Verdana; font-size: small"}
            Priority to be given for:
          %td{:style => "font-family: Verdana; font-size: small"}
            %select{:name => "cmbHoliday", :style => "width:100%;"}
              %option Weekly Holiday
              %option General Holiday
        %tr
          %td{:colspan => "2", :style => "font-family: Verdana; font-size: small; font-weight: bold;"}
            %hr/
            Advanced Settings
        %tr
          %td{:style => "font-family: Verdana; font-size: small"}
            Rotating Weekly Holiday
          %td{:style => "font-family: Verdana; font-size: small"}
            %input#cbRotWeekly{:type => "checkbox"}/
        %tr
          %td{:style => "font-family: Verdana; font-size: small"}
            Auto Allotment of Leave
          %td{:style => "font-family: Verdana; font-size: small"}
            %input#cbAutoAllot{:type => "checkbox"}/
        %tr
          %td{:style => "font-family: Verdana; font-size: small"}
            Consider CO and CW for Days calculation
          %td.style1{:style => "font-family: Verdana; font-size: small"}
            %input#cbCoCw{:type => "checkbox"}/
        %tr
          %td.style1{:colspan => "2", :style => "font-family: Verdana; font-size: small"}
            %hr/
        %tr
          %td.style1{:align => "right", :style => "font-family: Verdana; font-size: small"}
            %input#btnSave{:type => "button", :value => "Save"}/
          %td.style1{:style => "font-family: Verdana; font-size: small"}
            %input#btnCancel{:type => "button", :value => "Cancel"}/

app/views/leaves/index.html.haml
#page
  = render 'common'
  = render 'leavesettings'

app/views/timemanagements/show.html.haml
#page
  = render "common"
  #right-content
    = link_to "New Shift", new_timemanagement_url
    = render 'formShift'